import type { Card, StudyMaterial } from '../domain'

/*
 * 開発・動作確認用のダミーデータ（本物の試験問題ではない）。
 * 画像は public/images/samples/ にある、このプロジェクト用に作成した単純な SVG。
 */

const CREATED_AT = new Date('2026-10-01T00:00:00+09:00')
const SOURCE = '開発用ダミーデータ'

export const SAMPLE_CASTLE_MATERIAL_ID = 'sample-castle-3'
export const SAMPLE_TEST_MATERIAL_ID = 'sample-test'

export const SAMPLE_MATERIALS: readonly StudyMaterial[] = [
  {
    id: SAMPLE_CASTLE_MATERIAL_ID,
    title: '日本城郭検定3級',
    description: '開発用のダミー問題です。',
    isActive: true,
    newCardsPerDay: 10,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
  {
    id: SAMPLE_TEST_MATERIAL_ID,
    title: 'テスト用教材',
    description: '複数教材の切り替えと表示の確認用です。',
    isActive: true,
    newCardsPerDay: 5,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  },
]

type CardContent = Omit<Card, 'materialId' | 'order' | 'isArchived' | 'createdAt' | 'updatedAt'> &
  Partial<Pick<Card, 'isArchived'>>

function toCards(materialId: string, contents: readonly CardContent[]): Card[] {
  return contents.map((content, index) => ({
    isArchived: false,
    ...content,
    materialId,
    order: index + 1,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  }))
}

const CASTLE_CARDS = toCards(SAMPLE_CASTLE_MATERIAL_ID, [
  {
    id: 'castle-001',
    question: '城の中心となる曲輪を何という？',
    answer: '本丸',
    explanation: '城主の居所や天守が置かれることが多い、城の中核となる曲輪。',
    category: '城郭用語',
    tags: ['曲輪'],
    examDifficulty: 1,
    importance: 5,
    source: SOURCE,
  },
  {
    id: 'castle-002',
    question: '城の正面にあたる門を何という？',
    answer: '大手門（追手門）',
    explanation: '城の正面の出入口。裏手の門は搦手門という。',
    category: '城郭用語',
    tags: ['門'],
    examDifficulty: 1,
    importance: 4,
    source: SOURCE,
  },
  {
    id: 'castle-003',
    question: '城の裏手にあたる門を何という？',
    answer: '搦手門',
    explanation: '',
    category: '城郭用語',
    tags: ['門'],
    examDifficulty: 2,
    source: SOURCE,
  },
  {
    id: 'castle-004',
    question: '曲輪・堀・門などの配置を計画することを何という？',
    answer: '縄張り',
    explanation: '縄を張って配置を決めたことに由来するといわれる。',
    category: '縄張り',
    tags: ['用語'],
    examDifficulty: 1,
    importance: 5,
    source: SOURCE,
  },
  {
    id: 'castle-005',
    question: '本丸を二の丸・三の丸が同心円状に囲む縄張りの形式を何という？',
    answer: '輪郭式',
    explanation: '本丸が中心にあり、周囲を他の曲輪が取り囲む形式。',
    category: '縄張り',
    subcategory: '縄張りの形式',
    tags: ['縄張りの形式'],
    examDifficulty: 2,
    importance: 3,
    source: SOURCE,
  },
  {
    id: 'castle-006',
    question: '本丸・二の丸・三の丸を一直線に並べる縄張りの形式を何という？',
    answer: '連郭式',
    explanation: '',
    category: '縄張り',
    subcategory: '縄張りの形式',
    tags: ['縄張りの形式'],
    examDifficulty: 2,
    importance: 3,
    source: SOURCE,
  },
  {
    id: 'castle-007',
    question: '自然の石をほとんど加工せずに積む石垣の積み方を何という？',
    answer: '野面積み',
    explanation: '石の隙間には小石（間詰石）を詰める。',
    category: '石垣',
    subcategory: '積み方',
    tags: ['積み方'],
    examDifficulty: 1,
    importance: 4,
    source: SOURCE,
  },
  {
    id: 'castle-008',
    question: '石の接合面を加工し、隙間なく積む石垣の積み方を何という？',
    answer: '切込接ぎ',
    explanation: '',
    category: '石垣',
    subcategory: '積み方',
    tags: ['積み方'],
    examDifficulty: 2,
    importance: 4,
    source: SOURCE,
  },
  {
    id: 'castle-009',
    question: '石垣の角で、長方形の石の長辺と短辺を交互に組む積み方を何という？',
    answer: '算木積み',
    explanation: '石垣の隅（角）を強くするための積み方。',
    category: '石垣',
    subcategory: '隅の積み方',
    tags: ['積み方'],
    examDifficulty: 3,
    importance: 3,
    source: SOURCE,
  },
  {
    id: 'castle-010',
    question: '図のように、大きな屋根の上に物見（望楼）を載せた形式の天守を何という？',
    answer: '望楼型',
    explanation: 'この画像は開発用に作成した模式図です。',
    category: '天守',
    subcategory: '天守の形式',
    tags: ['天守の形式', '画像'],
    examDifficulty: 3,
    importance: 4,
    imageUrl: '/images/samples/castle-keep.svg',
    source: SOURCE,
  },
  {
    id: 'castle-011',
    question: '下の階から上の階へ規則的に小さくなるよう、同じ構造を積み重ねた天守の形式を何という？',
    answer: '層塔型',
    explanation: '',
    category: '天守',
    subcategory: '天守の形式',
    tags: ['天守の形式'],
    examDifficulty: 3,
    importance: 4,
    source: SOURCE,
  },
  {
    id: 'castle-012',
    question: '大天守と複数の小天守などを渡櫓で環状につないだ天守の形式を何という？',
    answer: '連立式',
    explanation: '',
    category: '天守',
    subcategory: '天守の構成',
    tags: ['天守の構成'],
    examDifficulty: 3,
    importance: 3,
    source: SOURCE,
  },
  {
    id: 'castle-013',
    question: '安土城を築いた武将は誰？',
    answer: '織田信長',
    explanation: '',
    category: '城郭史',
    tags: ['人物'],
    examDifficulty: 1,
    importance: 4,
    source: SOURCE,
  },
  {
    id: 'castle-014',
    question: '1615 年に江戸幕府が出した、大名の居城以外の城の破却を命じた法令を何という？',
    answer: '一国一城令',
    explanation: '',
    category: '城郭史',
    tags: ['法令', '江戸時代'],
    examDifficulty: 2,
    importance: 5,
    source: SOURCE,
  },
  {
    id: 'castle-015',
    question: '1873 年に明治政府が全国の城の存続・廃止を決めた通達を一般に何という？',
    answer: '廃城令',
    explanation: '',
    category: '城郭史',
    tags: ['法令', '明治時代'],
    examDifficulty: 2,
    importance: 4,
    source: SOURCE,
    notes: '開発用メモ：notes の表示確認用。',
  },
])

const TEST_CARDS = toCards(SAMPLE_TEST_MATERIAL_ID, [
  {
    id: 'test-001',
    question: '［テスト］1 + 1 は？',
    answer: '2',
    explanation: '最小限の項目だけを持つカード。',
    category: '基本',
    tags: [],
  },
  {
    id: 'test-002',
    question: '［テスト］額縁の中で、青い図形はどんな形？',
    answer: '円',
    explanation: 'この画像は開発用に作成した抽象図形です。',
    category: '画像',
    tags: ['画像'],
    examDifficulty: 1,
    importance: 1,
    imageUrl: '/images/samples/framed-shapes.svg',
    source: SOURCE,
  },
  {
    id: 'test-003',
    question:
      '［テスト］長い問題文の表示確認です。スマートフォンの狭い画面でも、問題文が途中で切れずに折り返して読みやすく表示されるかを確認します。\n改行を含む問題文も扱えます。',
    answer: '長い解答の表示確認です。\n改行を含む解答も扱えます。',
    explanation: '解説も複数行になる場合があります。\n2 行目の解説です。',
    category: '表示確認',
    subcategory: '長文',
    tags: ['長文', '改行'],
    examDifficulty: 5,
    importance: 2,
    notes: '表示確認用',
  },
  {
    id: 'test-004',
    question: '［テスト］カテゴリーが空のカード',
    answer: '「未分類」として扱われる',
    explanation: '',
    category: '',
    tags: [],
  },
  {
    id: 'test-005',
    question: '［テスト］アーカイブ済みのカード（出題されない）',
    answer: '—',
    explanation: '',
    category: '基本',
    tags: [],
    isArchived: true,
  },
])

export const SAMPLE_CARDS: readonly Card[] = [...CASTLE_CARDS, ...TEST_CARDS]
